[2025-06-29T20:33:11.294+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: superstore_etl_workflow.cargar_dim_tiempo manual__2025-06-29T20:04:38.635006+00:00 [queued]>
[2025-06-29T20:33:11.304+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: superstore_etl_workflow.cargar_dim_tiempo manual__2025-06-29T20:04:38.635006+00:00 [queued]>
[2025-06-29T20:33:11.305+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-06-29T20:33:11.323+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): cargar_dim_tiempo> on 2025-06-29 20:04:38.635006+00:00
[2025-06-29T20:33:11.329+0000] {standard_task_runner.py:60} INFO - Started process 874 to run task
[2025-06-29T20:33:11.333+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'superstore_etl_workflow', 'cargar_dim_tiempo', 'manual__2025-06-29T20:04:38.635006+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/superstore_etl_dag.py', '--cfg-path', '/tmp/tmpcjd4qovu']
[2025-06-29T20:33:11.336+0000] {standard_task_runner.py:88} INFO - Job 36: Subtask cargar_dim_tiempo
[2025-06-29T20:33:11.388+0000] {task_command.py:423} INFO - Running <TaskInstance: superstore_etl_workflow.cargar_dim_tiempo manual__2025-06-29T20:04:38.635006+00:00 [running]> on host 85c12c2be069
[2025-06-29T20:33:11.484+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='tu_nombre' AIRFLOW_CTX_DAG_ID='superstore_etl_workflow' AIRFLOW_CTX_TASK_ID='cargar_dim_tiempo' AIRFLOW_CTX_EXECUTION_DATE='2025-06-29T20:04:38.635006+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-29T20:04:38.635006+00:00'
[2025-06-29T20:33:11.487+0000] {logging_mixin.py:188} INFO - Iniciando ETL para la dimensión de tiempo desde Global_Superstore2.csv...
[2025-06-29T20:33:24.832+0000] {logging_mixin.py:188} INFO - Se extrajeron 51290 filas del archivo de origen.
[2025-06-29T20:33:24.834+0000] {logging_mixin.py:188} INFO - Transformando datos para d_tiempo...
[2025-06-29T20:33:24.858+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/superstore_etl_dag.py:282 UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
[2025-06-29T20:33:25.007+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/superstore_etl_dag.py:283 UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
[2025-06-29T20:33:25.181+0000] {logging_mixin.py:188} INFO - Se crearon 1468 registros únicos para d_tiempo.
[2025-06-29T20:33:25.182+0000] {logging_mixin.py:188} INFO - Cargando datos a BigQuery en la tabla d_tiempo...
[2025-06-29T20:33:28.319+0000] {logging_mixin.py:188} INFO - Carga completada. Se cargaron 1468 filas en la tabla tarea-sistemas-proceso-etl.dwh_superstore.d_tiempo.
[2025-06-29T20:33:28.320+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-06-29T20:33:28.336+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=superstore_etl_workflow, task_id=cargar_dim_tiempo, execution_date=20250629T200438, start_date=20250629T203311, end_date=20250629T203328
[2025-06-29T20:33:28.403+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-06-29T20:33:28.429+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
